version: "3"
services:
  goaccess:
      image: xavierh/goaccess-for-nginxproxymanager:latest
      container_name: goaccess
      restart: always
      environment:
          - TZ=America/New_York
          - SKIP_ARCHIVED_LOGS=False #optional
          - DEBUG=False #optional
          - BASIC_AUTH=True #optional
          - BASIC_AUTH_USERNAME=user #optional
          - BASIC_AUTH_PASSWORD=pass #optional
          - EXCLUDE_IPS=127.0.0.1 #optional - comma delimited list
          - LOG_TYPE=NPM #optional - more information below
      ports:
          - '7880:7880'
      volumes:
          - /opt/proxy/data/logs:/opt/log
          - /opt/proxy/data/logs:/opt/custom #optional, required if using log_type = CUSTOM
