version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      # Admin Web Port - After basic setup, allow only from localhost or intenal IP, NOT public internet! 
      #                - Default creds admin@example.com / changeme
      - '81:81'

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
